### ISSUE TITLE
使用 eslint 检查 typescript 代码

### ISSUE THREAD

**Issue by daychongyang** [daychongyang/awesome-react#3]

**Comment by daychongyang** [comment]
1. 基本依赖:
```json
{
	"eslint": "^5.16.0",
	"eslint-config-prettier": "^4.2.0",
	"eslint-loader": "^2.1.2",
	"eslint-plugin-react": "^7.12.4",
        "prettier": "^1.17.0",
	"pretty-quick": "^1.10.0",
        "@typescript-eslint/eslint-plugin": "^1.7.0",
	"@typescript-eslint/parser": "^1.7.0",
}
```

**Comment by daychongyang** [comment]
2. `.prettierrc`
```
{
	"arrowParens": "avoid",
	"bracketSpacing": true,
	"htmlWhitespaceSensitivity": "css",
	"insertPragma": false,
	"jsxBracketSameLine": false,
	"jsxSingleQuote": false,
	"printWidth": 80,
	"proseWrap": "preserve",
	"quoteProps": "preserve",
	"requirePragma": false,
	"semi": false,
	"singleQuote": true,
	"tabWidth": 2,
	"trailingComma": "none",
	"useTabs": true
}
```
**parser** 参数会影响`prettier` `json` 等文件格式控制台输出异常

**Comment by daychongyang** [comment]
3. `.eslintrc.yml`

```yml
env:
  browser: true
  es6: true
  node: true
extends:
  - 'prettier'
  - 'prettier/@typescript-eslint'
settings:
  react:
    version: detect
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  'no-console': 'off'
  indent:
    - error
    - tab
  linebreak-style: 'off'
  quotes:
    - error
    - single
  semi:
    - error
    - never

```
